name: build-windows-artifact

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: windows-2022  # پایدارتر از windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore "src/AI.SmartCut/AI.SmartCut.csproj" -r win-x64

      - name: Publish (Self-Contained)
        run: dotnet publish "src/AI.SmartCut/AI.SmartCut.csproj" -c Release -r win-x64 --self-contained true -o out/AI.SmartCut

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AI-SmartCut-Exe
          path: out/AI.SmartCut/**
          if-no-files-found: error
