name: Build AI SmartCut

on:
  workflow_dispatch:

jobs:
  build:
    # برای ثبات فعلاً به 2022 پین می‌کنیم (اعلامیه windows-latest رو بی‌اثر می‌کنه)
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore
        run: nuget restore AI.SmartCut.sln

      - name: Build (Release)
        run: msbuild AI.SmartCut.sln /t:Rebuild /p:Configuration=Release /m

      - name: Locate MSIX/Appx
        shell: pwsh
        run: |
          $pkg = Get-ChildItem -Recurse -Include *.msix,*.msixbundle,*.appx,*.appxbundle |
            Where-Object { $_.FullName -match "Release" } |
            Select-Object -First 1
          if (-not $pkg) { Write-Error "No MSIX/Appx found under Release"; exit 1 }
          "PKG=$($pkg.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Host "Package: $($pkg.FullName)"

      - name: Upload package (artifact v4)
        uses: actions/upload-artifact@v4
        with:
          name: AI-SmartCut-MSIX
          path: ${{ env.PKG }}
          if-no-files-found: error
