name: Build AI SmartCut

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true  # تا مدل بزرگ بیاد

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore src/AI.SmartCut/AI.SmartCut.csproj

    - name: Build
      run: dotnet publish src/AI.SmartCut/AI.SmartCut.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ai-smartcut
        path: src/AI.SmartCut/bin/Release/net8.0-windows/win-x64/publish/
